### ISSUE TITLE
autocomplete within phpstorm

### ISSUE THREAD

**Issue by michabbb** [driesvints/blade-icons#100]
hi there,

pardon, i know this is more a phpstorm question, so forgive me: 
is there any chance to let phpstorm know 
what custom `<x-icon-solid.arrow/>` tags exist and offer autocomplete for them ???

thanks for any hint!

**Comment by driesvints** [comment]
Hey @michabbb. Unfortunately not as there aren't any plugins for PHPStorm yet. I haven't created any PHPStorm plugins myself yet and probably won't have time to dig into that anytime soon. Maybe a community member is willing to contribute one.
