### ISSUE TITLE
Need to disable the exception of SvgNotFound in production

### ISSUE THREAD

**Issue by tokomeno** [driesvints/blade-icons#106]
Need to disable the exception of SvgNotFound in production

**Comment by driesvints** [comment]
You can't. It's meant to notify you that you're using an icon that's not available. What's your use case for referencing an icon that doesn't exists?

**Comment by LukasJK** [comment]
In my case - the user enters the icon name and it's displayed automatically. It would be great not to have an error pop-up if they enter the wrong name.
Using a fallback icon helps.
