### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by alexbarnsley** [driesvints/blade-icons#114]
Hi, would it possible to get a release, please? I would like to use the changes from #112

Thanks

**Comment by driesvints** [comment]
Yes soon I hope. I want to get in the performance improvements as well before I cut a 1.0.0 release.

**Comment by alexbarnsley** [comment]
No problem, thanks for the quick reply @driesvints!

**Comment by driesvints** [comment]
Btw, testing the feature already by pulling in dev-main is greatly appreciated. That way I can be sure it works as expected by users.
