### ISSUE TITLE
`alt` attribute not in SVG spec for alternative text.

### ISSUE THREAD

**Issue by meduzen** [driesvints/blade-icons#12]
Not in [SVG spec](https://www.w3.org/TR/SVG/attindex.html) nor [SVG2 spec](https://www.w3.org/TR/2016/CR-SVG2-20160915/attindex.html) too.

What matches with `alt` for SVG is the `<title>` tag as a child of the `<svg>` tag.

So, this:

```html
    @icon('cog', 'icon-lg', ['alt' => 'Gear icon']) Settings
```

should render as:

```
    <svg class="icon icon-lg">
        <title>Gear icon</title>
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#zondicon-cog"></use>
    </svg>
```

instead of:

```
    <svg class="icon icon-lg" alt="Gear icon">
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#zondicon-cog"></use>
    </svg>
```

There’s more resource about VG accessibility in [this Gist](https://gist.github.com/davidhund/564331193e1085208d7e) by @davidhund and in the comments. Haven’t read it yet.

I’m not familiar with issues and pull requests, but if I dig into it, I'll make one to contribute.

**Comment by driesvints** [comment]
Is this only necessary for sprites or also for regular svg's?

**Comment by meduzen** [comment]
It works for both. The `<title>` element is valid for all SVGs, no matter the other child(ren) element(s).

A useful resource with a lot of tests made is [_Creating Accessible SVGs_](https://www.deque.com/blog/creating-accessible-svgs/) by Carie Fisher, showing that `<title>` is the go-to SVG child element to use as alternative text for SVGs.

**Comment by meduzen** [comment]
(Double post and a bit off-topic.)

In the last years, I’ve stopped using Blade SVG and went for another straightforward SVG workflow. Gonna share it with you in the coming days. Don’t hesitate to ping if I forgot, this week is rather busy for me at ~~work~~ home.

**Comment by driesvints** [comment]
Thanks @meduzen, that's definitely helpful 👍

**Comment by driesvints** [comment]
I'm going to close this as I don't intend to implement this myself any time soon but happy to look at a PR if anyone wants to send one in which solves this in a clean way 👍
