### ISSUE TITLE
Why PHP 7.4

### ISSUE THREAD

**Issue by papalardo** [driesvints/blade-icons#12]
I dont understand why put min requirement php to 7.4. 

Im using 7.3 because multiples incompatibilites with 7.4 and min requirement Laravel 7.3.

And analysing base code, dont have some function that depends PHP 7.4.

Its not possible decrease min requirement php version ?

**Comment by driesvints** [comment]
The next iteration of blade-icons will be PHP 7.2: https://github.com/adamwathan/blade-svg/pull/50

**Comment by papalardo** [comment]
Ok, thanks for the answer.
