### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by xtreme2020** [driesvints/blade-icons#124]
### Library version

1.0.0

### Laravel version

8.29

### PHP version

7.4

### Description

In Container.php line 1057:

Unresolvable dependency resolving [Parameter #1 [ <required> string $manifestPath ]] in class BladeUI\Icons\IconsManifest

### Steps to reproduce

Install the package
 composer require blade-ui-kit/blade-icons

**Comment by driesvints** [comment]
Hey @xtreme2020. I can install the package just fine on a fresh install. Not sure why it's not working for you? 

```
$ composer require blade-ui-kit/blade-icons             ~/Sites/test-icons
Using version ^1.0 for blade-ui-kit/blade-icons
./composer.json has been updated
Running composer update blade-ui-kit/blade-icons
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking blade-ui-kit/blade-icons (1.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing blade-ui-kit/blade-icons (1.0.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: blade-ui-kit/blade-icons
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/sail
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
75 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by csoutham** [comment]
@xtreme2020 Do you have any other icon packs installed?
I have the same issue when installed (or updating) with the Font Awesome pack (owenvoke/blade-fontawesome)

**Comment by driesvints** [comment]
@csoutham did you have the same issue when installing fresh? Are you installing blade-icons and blade-fontawesome together?

**Comment by csoutham** [comment]
@driesvints I've tried them separately and together, installing from fresh.
blade-icons installs with no issues but adding (or on it's own) blade-fontawesome causes this error:

```
@php artisan package:discover --ansi

In Container.php line 1064:
Unresolvable dependency resolving [Parameter #1 [ <required> string $manifestPath ]] in class BladeUI\Icons\IconsManifest
```

**Comment by driesvints** [comment]
I'll take another look when I find some time. Thanks for mentioning.

**Comment by driesvints** [comment]
I can't recreate this sorry. I've tried installing blade icons and blade-fontawesome separately and together and it always goes well for me. I'll need more specific installation instructions in order to reproduce this.

**Comment by csoutham** [comment]
@driesvints Thanks, it looks like a change at the blade-fontawesome end has resolved this!
Thanks for taking the time to look into, I'm getting no issues upgrading now.

**Comment by driesvints** [comment]
@csoutham glad you got it fixed! : )

**Comment by chrispymm** [comment]
Wasn't sure whether to open a new issue or comment here, but I am having the same issue.  I'm not trying to use fontawesome though, but heroicons.

**Library Version:** 1.0.2
**Laravel Version:** 8.42.1 
**PHP Version:** 7.4.4

```
In Container.php line 1067:
Unresolvable dependency resolving [Parameter #1 [ <required> string $manifestPath ]] in class BladeUI\Icons\IconsManifest
```

**What I've tried:**
composer require blade-ui-kit/blade-heroicons - gives the error above
composer require blade-ui-kit/blade-icons - gives the error above

I've cleared all the caches as recommended before installing and still getting the error..

However in a fresh Laravel install both worked, so I realise this is not necessarily a bug with the library, but something local to my app.  However I am unsure of where to start debugging what could casue this issue.  Do you have any suggestions? Could another package be causing this? (I'm not sure how!).   Any help gratefully received, but understand if you can't as you probably can't reproduce the error. Thanks

**Comment by driesvints** [comment]
I'm very sorry @chrispymm but I'll need a way to reproduce this otherwise I'm really out of clues 🙁

**Comment by chrispymm** [comment]
No worries @driesvints, I thought that would be the case as it's clearly nothing wrong in your library, and must be something in my project.

As it happens I ran a composer update this morning, noticed a dependency update and went to read the release notes and found it included a PR to fix [this issue](https://github.com/area17/twill/issues/943).

**Comment by driesvints** [comment]
@chrispymm thanks for mentioning that. The actual issue is that that library is resolving dependencies in `register` in a service provider. You should never do that because `register` is for registration of dependencies only.
