### ISSUE TITLE
 Undefined index: disk

### ISSUE THREAD

**Issue by olivM** [driesvints/blade-icons#129]
### Library version

1.0.x

### Laravel version

5.8

### PHP version

7.4

### Description

  Undefined index: disk

  at vendor/blade-ui-kit/blade-icons/src/BladeIconsServiceProvider.php:50
     46▕                 $config,
     47▕             );
     48▕
     49▕             foreach ($config['sets'] ?? [] as $set => $options) {
  ➜  50▕                 if (! isset($options['disk']) && ! $options['disk']) {
     51▕                     $paths = $options['paths'] ?? $options['path'] ?? [];
     52▕
     53▕                     $options['paths'] = array_map(
     54▕                         fn ($path) => $app->basePath($path),

      +23 vendor frames
  24  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Spatie\CookieConsent\CookieConsentServiceProvider))

      +5 vendor frames
  30  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

### Steps to reproduce

composer require blade-ui-kit/blade-icons

**Comment by driesvints** [comment]
Thanks, I'll try to pick this up asap.

**Comment by driesvints** [comment]
I pushed a new release which fixes this. Thanks
