### ISSUE TITLE
Add a default function or php class that can run when calling an icon

### ISSUE THREAD

**Issue by roni-estein** [driesvints/blade-icons#132]

**Comment by roni-estein** [comment]
I'd love to be able to have a place where I could parse the data I'm calling on the icon and decide what classes I'm applying. Here is a use case. Depending on the libraries you are using, I'm using tailwindcss2.x at this moment, I am declaring default sizes of h-5 w-5 for my design. In this case it makes sense. If I apply another larger size h-6 w-6 in some cases it works flawlessly but both classes will actually be rendered in the html and depending on the rendered order in tailwind the last one will dominate. However if tailwind were to change its ordering or if I needed to use h-4 w-4 I would not be able to, wince the default h-5 w-5 would cascade over them.

I'd love a place to detect if I am running certain classes and if I am not apply the defaults, but if I am overwrite them.

Let's say for example, I Always want flex-shrink-0 to be applied to my classes, but only apply sizes if there was no classes present. It would be cool if I could either work that into the config file in some way. Perhaps in some always present key. Then leave the default classes key for the default values, the ones that are only added when other classes are not specified. Either that, or specify in some way the name of a class or function that has accessible parameters that will allow a user to make those determinations on their own.

**Comment by driesvints** [comment]
I'd like to avoid this extra complexity in the package tbh. In this case I recommend not setting the defaults and using a Blade component:

```blade
@props(['name', 'class' => 'normal-defaults'])

<x-icon :name="$name" :class="$class" />
```

Usage:

```blade
<x-my-icon name="your-icon" class="overwritten-defaults" />
```

Does that help?

**Comment by roni-estein** [comment]
Oh, that's very clever and actually much more similar to what I was using before I started using blade icons, to begin with. I guess the pros in that situation are:

- you can control every aspect of it (exactly what I wanted)
- you have icon caching, so there is no bloated loading time even with 9000 icons which is a plus
- more declarative

the cons 
- it breaks away from the convention of what people are expecting when they see the blade icon package
- longer syntax

I kind of wish this was built in, and I could override the default behaviour somewhere to keep the original interface the same. But if there is no chance of that, this is a decent compromise. Still hoping 🤞

**Comment by driesvints** [comment]
Yeah I believe this is a bit stretching the limits of what the package is intended for. Since there's a decent workaround I'm going to leave this be.
