### ISSUE TITLE
Found duplicate icon-package for `simpleicons` in README.md

### ISSUE THREAD

**Issue by swapnilsarwe** [driesvints/blade-icons#134]
Hello @driesvints ,

I guess the icon package for `https://simpleicons.org/` which I created under the name [Blade Simple Icons](https://github.com/codeat3/blade-simple-icons), also existed with the name [Blade Brand Icons](https://github.com/sadegh19b/blade-brand-icons).

I think I will update my `README.md`with the steps to migrate to the `Blade Brand Icons` package and archive my package to avoid the duplicates.

Need your suggestion?

**Comment by driesvints** [comment]
Thanks. I've removed yours from the readme. I'll leave it up to @sadegh19b to decide if he wants to rename his package to Simple Icons.

**Comment by swapnilsarwe** [comment]
Works.
I will update my `README.md` to migrate to the @sadegh19b package.
