### ISSUE TITLE
Unable to locate a class or view for component XXX

### ISSUE THREAD

**Issue by jeanali** [driesvints/blade-icons#137]
Hi, just install the package as follow:

```
- composer require blade-ui-kit/blade-icons
- php artisan vendor:publish --tag=blade-icons
```

Then in I blade  put ```<x-icon-camera/>``` got this error:

```
 Unable to locate a class or view for component [icon-camera]. 
```

What should I do next, cuz I read the docs and I do not fully understand it! :(

**Comment by driesvints** [comment]
Did you uncomment the default icon set in the `blade-icons.php` config file as stated in the installation docs?

**Comment by jeanali** [comment]
Yeah, I did. but still, getting the same error

**Comment by driesvints** [comment]
Did you put the camera svg in the `resources/svg` directory?

**Comment by simonbuehler** [comment]
does one have to copy every single used icon to the resources/svg directory? isn't there a way to resove this from the package somehow? somehow as comfortable as compiling css files and shaking tree ?

**Comment by driesvints** [comment]
@simonbuehler what do you mean? Icons are always resolved from a directory with this package. What does this have to do with CSS?

**Comment by simonbuehler** [comment]
i was misunderstanding that blade-icons don't ship any icons and instead of e.g. `<x-icon-o-adjustments/>` i had to use `<x-heroicon-o-adjustments/>` and then the icon was resolved from the heroicon package.

i thought one had to copy all the svgs manually into the `resources/svg` directory which is wrong.  in this  context i refered to only bundling / copying for release / ... the few needed files instead of the whole set but as it lives in `vendor` and not the `app/resources/svg` this is also bullshit, just ignore this, sorry & thanks

**Comment by driesvints** [comment]
@simonbuehler btw, you can just require blade-heroicons if you only need the Heroicons package and aren't using icons in a specific directory of your own. Also definitely feel free to say if the docs aren't clear. Happy to improve them 🙂

**Comment by driesvints** [comment]
@jeanali Closing this one. Feel free to reply when you can.

**Comment by michabbb** [comment]
today i faced a similar problem: when calling `artisan optimize` i get the same error:

```
Unable to locate a class or view for component [bs-arrow-right-square-fill].
```

in one of my templates I am using: 

```html
<x-bs-arrow-right-square-fill></x-bs-arrow-right-square-fill>
````

icons are located in `resources/svg/bootstrapicons` and my config:

```php
<?php

return [
    'sets' => [
        'heroicons' => [
            'path' => 'resources/svg/heroicons',
            'prefix' => 'hero'
        ],
        'bootstrapicons' => [
            'path' => 'resources/svg/bootstrapicons',
            'prefix' => 'bs'
        ]
  ]
];
```

thanks for any help!

**Comment by driesvints** [comment]
@michabbb Can you open a new issue please?

**Comment by michabbb** [comment]
@driesvints done ▶️ #147

**Comment by warmwhisky** [comment]
> Did you put the camera svg in the `resources/svg` directory?

Where do you get the icons? I see no way to get them? I was trying to use `<x-forkawesome-braille />` and also executed `composer require codeat3/blade-forkawesome` but I still get `Unable to locate a class or view for component `

What am I missing?
