### ISSUE TITLE
Use dot notation in the directive

### ISSUE THREAD

**Issue by ericlbarnes** [driesvints/blade-icons#14]
I have a project that has a ton of svg's. So I put them in `svg/{pagename}/*`. 

In normal Laravel fashion, I'd assume something like this would work: `@icon('pricing.ic-api')` but it fails. You have to fall back to the slash `@icon('pricing/ic-api')`

You should fix this so I can sleep well this weekend, which always to be my birthday weekend. No pressure, but I think you'd feel bad if I didn't sleep for 48 hours and then was angry with my family. 

Think of the children Adam!

**Comment by adamwathan** [comment]
DON'T YOU DARE CLOSE ISSUES ON MY REPOSITORY!!!!

https://github.com/adamwathan/blade-svg/commit/3ec8f970a4145350bd99cb021b1ea8a1833647ce
