### ISSUE TITLE
Unable to locate a class or view for component

### ISSUE THREAD

**Issue by michabbb** [driesvints/blade-icons#147]
today i faced a similar problem like #137 
while calling `artisan optimize`.

```
Unable to locate a class or view for component [bs-arrow-right-square-fill].
```

in one of my templates I am using: 

```html
<x-bs-arrow-right-square-fill></x-bs-arrow-right-square-fill>
````

icons are located in `resources/svg/bootstrapicons` and my config:

```php
<?php

return [
    'sets' => [
        'heroicons' => [
            'path' => 'resources/svg/heroicons',
            'prefix' => 'hero'
        ],
        'bootstrapicons' => [
            'path' => 'resources/svg/bootstrapicons',
            'prefix' => 'bs'
        ]
  ]
];
```

thanks for any help!

- Library Version: 0.4.5
- Laravel Version: v8.9.0
- PHP Version: 7.4.9

**Comment by driesvints** [comment]
Can you upgrade to v1.0 of the library? I don't really intend to provide support for anything lower sorry.

**Comment by driesvints** [comment]
Feel free to reply if you're also experiencing this with v1.0 👍

**Comment by michabbb** [comment]
@driesvints sorry, i will test, i wasn´t able till today....

**Comment by gmarineau** [comment]
Same problem here : Unable to locate a class or view for component [bx-arrow-back].

 "blade-ui-kit/blade-icons": "^1.8"
 "blade-ui-kit/blade-ui-kit": "^0.6.4"
 "mallardduck/blade-boxicons": "^2.4"
