### ISSUE TITLE
Build template repo for Icon packages

### ISSUE THREAD

**Issue by driesvints** [driesvints/blade-icons#158]
A template repo for icon packages could allow them to get started even faster with building new packages.

To investigate when https://github.com/blade-ui-kit/blade-icons/pull/144 is merged.

**Comment by ssmusoke** [comment]
This would be awesome as I have been struggling to get started for an icon library I would like to get added 

Thank you for the excellent job you are doing

**Comment by driesvints** [comment]
Done: https://github.com/blade-ui-kit/blade-icons-template
