### ISSUE TITLE
Config not being publish by the service provider

### ISSUE THREAD

**Issue by giovannipds** [driesvints/blade-icons#16]
Hello.
It seems the service provider is not publishing the config file at config/ dir for me. Laravel 5.4.
Any suspects why? Is that occurring to anyone else as well or just me?

**Comment by adamwathan** [comment]
Make sure you register the service provider in config/app.php before trying to publish the config, should work then 👍

**Comment by giovannipds** [comment]
@adamwathan I've done that, and it didn't work. =( I've used the package on a Laravel 5.2 or 5.3 app and it worked nicely, but on a recent one, in 5.4, it was not publishing. I'm gonna try again tomorrow but I don't have much faith it'll be different.
Also, trying to create the config file myself hasn't allowed the `@icon` helper anyway. =S Weird.

**Comment by adamwathan** [comment]
Hmm I just created a brand new 5.4 project and had no issues. Definitely give it another try and if it doesn't work, publish the repository on GitHub so I can take a look.

**Comment by giovannipds** [comment]
@adamwathan hey Adam. I've tested now, and it's working fine.

When I was running `php artisan vendor:publish --provider="BladeSvg\BladeSvgServiceProvider"`, it wasn't copying the file `blade-svg.php`, although it was showing the `Publishing complete` message. Testing it again today, I could see the message `Copied File [\vendor\nothingworks\blade-svg\config\blade-svg.php] To [\config\blade-svg.php]`.

I think it was just a Laravel config cache issue (solved by `php artisan config:clear`, if anyone else fell here).

Thanks for helping me by, and sorry for it being such an stupid error. I'm gonna close the issue. =)

Thanks!

**Comment by giovannipds** [comment]
It has happened again with the latest release (not the dev-master). With the dev-master everything worked like a charm. =)
