### ISSUE TITLE
Wrap icons with <span>?

### ISSUE THREAD

**Issue by RishabSwift** [driesvints/blade-icons#161]
Hello,

Is it currently possible to wrap all icons with a `<span>....</span>` tag without manually wrapping each one?

Like for instance...  doing `<x-icon-home class="my-custom-wrapper-class">` would generate

     <span class="my-custom-wrapper-class"><x-icon-home/><span>

I've tried manually wrapping each `<svg>....</svg>` with `<span>` tags but the Default Set Class only applies to the `svg` element.

Thanks a lot!

**Comment by driesvints** [comment]
Hey @RishabSwift. That's out of scope for this package I'm afraid. But you can solve this with Blade Icons itself. 

You can define a `wrapped-icon` anonymous component like this:

```blade
 <span class="my-custom-wrapper-class">
    <x-icon :class="$name" />
<span>
```

And then use it like:

```blade
<x-wrapped-icon name="home" />
```

And all of the icons you use like that will have the span element around them. I do want to remind you that you can already set classes on icons itself, including default classes through the config on either the global level or the icon set level: https://github.com/blade-ui-kit/blade-icons#default-classes
