### ISSUE TITLE
New package to be included in the list

### ISSUE THREAD

**Issue by troccoli** [driesvints/blade-icons#168]
Hello,

I have created a package to use the Health Icons (https://healthicons.org/) with blade: https://github.com/troccoli/blade-health-icons.

Would it be possible to add it to the list?

Thanks

**Comment by driesvints** [comment]
Done 👍 

Next time feel free to send in a PR. Also feel free to send in a PR to the blade-ui-kit.com repo to add them to the icon search. Here's an example commit of how that can be done: https://github.com/blade-ui-kit/blade-ui-kit.com/commit/56b062fc58ab95da649ebf60be6b161e85641ad3
