### ISSUE TITLE
Blade Icons breaks Laravel Jetstream

### ISSUE THREAD

**Issue by Flobbos** [driesvints/blade-icons#175]
### Library version

1.1

### Laravel version

8.54

### PHP version

7.4

### Description

Error: Unable to find component: [profile.update-profile-information-form]

As soon as you uninstall Blade Icons everything goes back to normal. 

I have discovered that in the JetstreamServiceProvider on line 40:

`$this->app->afterResolving(BladeCompiler::class, function () {
            
            if (config('jetstream.stack') === 'livewire' && class_exists(Livewire::class)) {
                Livewire::component('navigation-menu', NavigationMenu::class);
                Livewire::component('profile.update-profile-information-form', UpdateProfileInformationForm::class);
                Livewire::component('profile.update-password-form', UpdatePasswordForm::class);
                Livewire::component('profile.two-factor-authentication-form', TwoFactorAuthenticationForm::class);
                Livewire::component('profile.logout-other-browser-sessions-form', LogoutOtherBrowserSessionsForm::class);
                Livewire::component('profile.delete-user-form', DeleteUserForm::class);

                if (Features::hasApiFeatures()) {
                    Livewire::component('api.api-token-manager', ApiTokenManager::class);
                }

                if (Features::hasTeamFeatures()) {
                    Livewire::component('teams.create-team-form', CreateTeamForm::class);
                    Livewire::component('teams.update-team-name-form', UpdateTeamNameForm::class);
                    Livewire::component('teams.team-member-manager', TeamMemberManager::class);
                    Livewire::component('teams.delete-team-form', DeleteTeamForm::class);
                }
            }
        });`

This code block is no longer executed when blade icons is installed. 

### Steps to reproduce

This issue should be relatively simple to reproduce:

- create a new Laravel 8 project
- install Jetstream with the Livewire stack
- install Blade Icons
- Log into the admin area
- Click on your name -> profile

**Comment by driesvints** [comment]
Works fine for me. Used the exact steps to reproduce.

**Comment by xtfer** [comment]
I have the same issue, FWIW, but I can't track down the cause. Adding blade-icons to a pre-existing Jetstream Livewire project causes all namespaced component paths to disappear, consistently.

However, I couldn't repeat it using the Steps above, so I'm at a bit of a loss as to how to debug it.

**Comment by xtfer** [comment]
This has something to do with the order the Service Providers are loaded in. I can resolve this by opting out of package discovery for the Blade UI Kit, and adding the provider manually.

In **composer.json**

```
"extra": {
    "laravel": {
        "dont-discover": [
            "blade-ui-kit/blade-icons"
            ]
        }
    },
```

In **app.php**
```
'providers' => [
    BladeUIKit\BladeUIKitServiceProvider::class,
    ...
]
```

**Comment by xtfer** [comment]
Tracked this down eventually.

The error was that the directory for the default set was missing (`resources/svg`), however this error was being masked by a the missing namespaces error.

**Comment by Flobbos** [comment]
I eventually fixed the problem by moving all of the Jetstream component registrations into the AppServiceProvider. There was no other way around it.
