### ISSUE TITLE
Question: should caching be advocated more prominently?

### ISSUE THREAD

**Issue by SebastianSchoeps** [driesvints/blade-icons#181]
### Library version

1.1.2

### Laravel version

8.73.0

### PHP version

8.0

### Description

Hey all,

first of all: thanks for the great package!

I just spent several hours trying to figure out why the performance of my app was so slow. I went thought the whole Laravel kernel (actually I learned a lot) until I finally got to the point that this is caused by me using large icon sets. I know this is handled in the documentation, but in my case I use quite a number of packages and had a very tough time.

To help my future me and others - would a PR containing something like the following make sense?

**Before:**
```
public function registerComponents(): void
{
    if ($this->config['components']['disabled']) {
        return;
    }

    foreach ($this->manifest->getManifest($this->sets) as $set => $paths) {
        foreach ($paths as $icons) {
            foreach ($icons as $icon) {
                Blade::component(
                    SvgComponent::class,
                    $icon,
                    $this->sets[$set]['prefix'] ?? '',
                );
            }
        }
    }
}
```
**After:**
```
public function registerComponents(): void
{
    if ($this->config['components']['disabled']) {
        return;
    }

    $time = microtime(true);

    foreach ($this->manifest->getManifest($this->sets) as $set => $paths) {
        foreach ($paths as $icons) {
            foreach ($icons as $icon) {
                Blade::component(
                    SvgComponent::class,
                    $icon,
                    $this->sets[$set]['prefix'] ?? '',
                );
            }
        }
    }

    if(app()->environment() != 'production'
        && $this->config['components']['performance-exception-enabled']
        && microtime(true) - $time > $this->config['components']['performance-exception-time']
        && !\File::exists($this->getManifestPath()))
    {
        throw new SlowComponentRegisteringException(
            "Registering the blade icon components took very long. You should cache your icons (see website).
            You can surpress this exception by setting config['components']['performance-exception-enabled'] to false.");
    }
}
```

### Steps to reproduce

-

**Comment by driesvints** [comment]
Hey @SebastianSchoeps. I appreciate the thought but I don't think we should start throwing exceptions for this. Caching is clearly described in the docs. Whenever you use a library, it's best to spend some time reading them as OS maintainers tried their best writing them.

**Comment by SebastianSchoeps** [comment]
@driesvints Thanks for your quick reply. However, the problem here is that the issue might get the developer's attention long after the package was installed (and I certainly don't remember every readme of every package). For me, it's not a problem anymore - but I guess others will run into this too and spend hours, because you only see slow performance in your app that is very hard to debug. And if you don't recognize it you lose a 100ms or so without ever knowing.
Another mitigation would be to just enable caching by default on the first request. And make it configurable to disable it (whatever the reason might be that you don't want to use it). Then you might have the issue that icons are not available after installing new ones or after deploying - but at least you know where to look and see the caching issue immediately in the docs.
