### ISSUE TITLE
Icon set should not be registered in console

### ISSUE THREAD

**Issue by AidasK** [driesvints/blade-icons#182]
### Library version

1.1.2

### Laravel version

8.63.0

### PHP version

8.0

### Description

I have a CI job which must run some artisan commands before installing node modules and my svg icons are installed through npm. My ci flow:
```sh
php artisan vendor:publish --tag=assets
php artisan airdrop:download
npm i
npm run production
php artisan airdrop:upload
```
And this flow does not work, because artisan breaks with:
```
 BladeUI\Icons\Exceptions\CannotRegisterIconSet

  The [/var/www/node_modules/bootstrap-icons/icons] path for the "bi" set does not exist.
```
<img width="739" alt="image" src="https://user-images.githubusercontent.com/2088484/145894101-5647c5ad-e1ae-4967-9da9-3fdfcb8b013c.png">

I think it would be a huge improvement since jobs and other console commands does not need this lib loaded. Not sure why it's happeneing in this case. Would it be possible to make this lib load only on the first usage? E.g. first requested svg icon on the blade?

Even composer install fails if node_modules are not installed in this case:
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/2088484/145894875-05867012-5039-424d-9296-fd5dbdc981a5.png">

### Steps to reproduce

```sh
php artisan vendor:publish --tag=assets
php artisan airdrop:download
npm i
npm run production
php artisan airdrop:upload
```

**Comment by driesvints** [comment]
I'm very sorry but this is a workflow we cannot accommodate for. Actually, it's common that icons are still available when running an app through the CLI as there could be jobs generating reports, building mailable, etc that still require the icons to be rendered.

Can't you run `npm i` before the artisan commands?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
