### ISSUE TITLE
Cannot register icon set 

### ISSUE THREAD

**Issue by labomatik** [driesvints/blade-icons#184]
### Library version

v1.2.0

### Laravel version

v8.69

### PHP version

v8.0

### Description

When deploying my app using envoyer.io i'm getting an error:

`
BladeUI\Icons\Exceptions\CannotRegisterIconSet: The options for the "fluentui-system-icons" set don't have a prefix defined.
#47 /vendor/blade-ui-kit/blade-icons/src/Exceptions/CannotRegisterIconSet.php(23): BladeUI\Icons\Exceptions\CannotRegisterIconSet::prefixNotDefined
#46 /vendor/blade-ui-kit/blade-icons/src/Factory.php(64): BladeUI\Icons\Factory::add
#45 /vendor/codeat3/blade-fluentui-system-icons/src/BladeFluentUiSystemIconsServiceProvider.php(20): Codeat3\BladeFluentUiSystemIcons\BladeFluentUiSystemIconsServiceProvider::Codeat3\BladeFluentUiSystemIcons\{closure}
#44 /vendor/laravel/framework/src/Illuminate/Container/Container.php(1269): Illuminate\Container\Container::fireCallbackArray
#43 /vendor/laravel/framework/src/Illuminate/Container/Container.php(1234): Illuminate\Container\Container::fireAfterResolvingCallbacks
#42 /vendor/laravel/framework/src/Illuminate/Container/Container.php(1219): Illuminate\Container\Container::fireResolvingCallbacks
#41 /vendor/laravel/framework/src/Illuminate/Container/Container.php(778): Illuminate\Container\Container::resolve
#40 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Foundation\Application::resolve
#39 /vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Container\Container::make
#38 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Foundation\Application::make
#37 /vendor/blade-ui-kit/blade-icons/src/BladeIconsServiceProvider.php(66): BladeUI\Icons\BladeIconsServiceProvider::BladeUI\Icons\{closure}
#36 /vendor/laravel/framework/src/Illuminate/Container/Container.php(1269): Illuminate\Container\Container::fireCallbackArray
#35 /vendor/laravel/framework/src/Illuminate/Container/Container.php(1234): Illuminate\Container\Container::fireAfterResolvingCallbacks
#34 /vendor/laravel/framework/src/Illuminate/Container/Container.php(1219): Illuminate\Container\Container::fireResolvingCallbacks
#33 /vendor/laravel/framework/src/Illuminate/Container/Container.php(778): Illuminate\Container\Container::resolve
#32 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Foundation\Application::resolve
#31 /vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Container\Container::make
#30 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Foundation\Application::make
#29 /vendor/laravel/framework/src/Illuminate/Container/Container.php(1423): Illuminate\Container\Container::offsetGet
#28 /app/Providers/HtmlServiceProvider.php(18): App\Providers\HtmlServiceProvider::App\Providers\{closure}
#27 /vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\Container\Container::build
#26 /vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container::resolve
#25 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Foundation\Application::resolve
#24 /vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Container\Container::make
#23 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Foundation\Application::make
#22 /vendor/laravel/framework/src/Illuminate/Container/Container.php(1423): Illuminate\Container\Container::offsetGet
#21 /app/Providers/HtmlServiceProvider.php(29): App\Providers\HtmlServiceProvider::App\Providers\{closure}
#20 /vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\Container\Container::build
#19 /vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container::resolve
#18 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Foundation\Application::resolve
#17 /vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Container\Container::make
#16 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Foundation\Application::make
#15 /vendor/laravel/framework/src/Illuminate/Container/Container.php(1423): Illuminate\Container\Container::offsetGet
#14 /vendor/anhskohbo/no-captcha/src/NoCaptchaServiceProvider.php(30): Anhskohbo\NoCaptcha\NoCaptchaServiceProvider::boot
#13 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#12 /vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\Util::unwrapIfClosure
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\BoundMethod::callBoundMethod
#10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::call
#9 /vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\Container::call
#8 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\Foundation\Application::bootProvider
#7 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\Foundation\Application::Illuminate\Foundation\{closure}
#6 [internal](0): array_walk
#5 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): Illuminate\Foundation\Application::boot
#4 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Bootstrap\BootProviders::bootstrap
#3 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Application::bootstrapWith
#2 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Console\Kernel::bootstrap
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\Foundation\Console\Kernel::handle
#0 /artisan(37): null
`

Here is how i'm deploying:
- composer install
- cd {{ release }}
- php artisan horizon:publish
- php artisan schedule-monitor:sync
- php artisan config:cache
- php artisan route:cache
- php artisan view:cache
- php artisan icons:clear
- php artisan icons:cache

I saw a ticket explaining that we need to clear the cache before installing; is it composer? 
what will happen in prod because the cache is on redis and envoyer ony activate the release when composer is installed and sources cloned.

Thanks for your help

### Steps to reproduce

Deployement via envoyer with icon caching

**Comment by driesvints** [comment]
A couple of things here:

- `php artisan horizon:publish` should be run locally and committed to your repo
- Caching should be done before running other commands because other commands may invoke libraries like Blade Icons which can run into issues like this.

Try:

- composer install
- cd {{ release }}
- php artisan config:cache
- php artisan icons:cache
- php artisan route:cache
- php artisan view:cache
- php artisan horizon:publish
- php artisan schedule-monitor:sync

**Comment by driesvints** [comment]
Here's the deploy pipeline from Laravel.io:

<img width="1247" alt="Screenshot 2022-01-31 at 11 09 09" src="https://user-images.githubusercontent.com/594614/151775339-a17393e7-2f32-456d-800a-ba2aa9693bb1.png">

**Comment by labomatik** [comment]
That fixed it ;-)
Many thanks @driesvints  for sharing your pipeline
