### ISSUE TITLE
Installation with Sage 10 theme

### ISSUE THREAD

**Issue by minemindmedia** [driesvints/blade-icons#188]
### Library version

Latest

### Laravel version

Latest

### PHP version

7.4.26

### Description

Hi, I apologize in advance if there is no support allowed here for installation via the Sage10 theme for WordPress. Laravel is extremely new for me.
https://github.com/roots/sage/tree/v10.1.1

I am attempting to install this package with the latest release of Sage 10 theme (via Acorn):
https://roots.io/acorn/

### Steps to reproduce

From the Sage theme directory I have installed this package successfully along with the heroicons package:

```
 "require": {
    "php": "^7.4|^8.0",
    "blade-ui-kit/blade-heroicons": "^1.3",
    "blade-ui-kit/blade-icons": "^1.2",
    "log1x/acf-composer": "^2.0",
    "log1x/navi": "^2.0",
    "log1x/poet": "^2.0",
    "log1x/sage-directives": "^1.1",
    "log1x/sage-html-forms": "^1.0"
  },
```

Within my `navigation.blade.php` view, I've included the following:
` <x-heroicon-o-adjustments class="w-6 h-6 text-gray-500"/>`

```
<div class="flex flex-wrap">
  @foreach ($item->children as $child)
    <div class="w-1/3">
      <a href="#" class="flex flex-col justify-between p-4 -m-3 transition duration-150 ease-in-out rounded-lg ">
        <div class="flex p-4 border border-gray-300 hover:bg-gray-100">
          <div class="inline-flex items-center justify-center w-32 mr-4">
            <img src="https://mlclell2icph.i.optimole.com/Zy7-GZE.CU8U~4e10/w:2000/h:1500/q:80/https://www.marlinmag.com/wp-content/uploads/sites/15/2021/09/blue-marlin-tahiti-fishing-surface.jpg" alt="">
                  </div>
                <div class="flex flex-col">
              <div class="text-lg font-medium">{!! $child->label !!}</div>
            <x-heroicon-o-adjustments class="w-6 h-6 text-gray-500"/>
          </div>
        </div>
      </a>
    </div>
  @endforeach
</div>
```

Symfony error output produces:
`Unable to locate a class or view for component [heroicon-o-adjustments]. (View: /srv/www/sage10.com/current/web/app/themes/sage10/resources/views/partials/navigation.blade.php)`

I've also added the directives which don't appear to be recognized:
`@bukStyles` and `@bukScripts`

Although the docs state this isn't necessary, I've attempted to publish the following:
`php artisan vendor:publish --tag=blade-ui-kit-config`
but my project doesn't recognize `artisan`

Here's a list of my current providers. Is there a way I can manually add the provider here?

```
'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        // Illuminate\Auth\AuthServiceProvider::class,
        // Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        // Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        // Illuminate\Cookie\CookieServiceProvider::class,
        // Illuminate\Database\DatabaseServiceProvider::class,
        // Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        // Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        // Illuminate\Hashing\HashServiceProvider::class,
        // Illuminate\Mail\MailServiceProvider::class,
        // Illuminate\Notifications\NotificationServiceProvider::class,
        // Illuminate\Pagination\PaginationServiceProvider::class,
        // Illuminate\Pipeline\PipelineServiceProvider::class,
        // Illuminate\Queue\QueueServiceProvider::class,
        // Illuminate\Redis\RedisServiceProvider::class,
        // Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        // Illuminate\Session\SessionServiceProvider::class,
        // Illuminate\Translation\TranslationServiceProvider::class,
        // Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        Roots\Acorn\Providers\AcornServiceProvider::class,
        Log1x\Navi\Providers\NaviServiceProvider::class,
        Log1x\HtmlForms\HtmlFormsServiceProvider::class,
        Log1x\AcfComposer\Providers\AcfComposerServiceProvider::class,
        Log1x\Poet\PoetServiceProvider::class,

        /*
         * Package Service Providers...
         */

        /*
         * Application Service Providers...
         */
        // App\Providers\ThemeServiceProvider::class,

    ],
```

**Comment by minemindmedia** [comment]
Sometimes all it takes is for me to write up a big report until something clicks. 
After posing this I immediately found a way to publish this manually. Perhaps there is a better solution but here is what worked for me with Sage10.

-----

If you’re looking to get Blade UI Kit icons setup within Sage 10 here is the process I took.

via Sage theme: composer require blade-ui-kit/blade-icons

Choose any additional icon sets you may want to include. In this cased I chose heroicons:


[GitHub](https://github.com/blade-ui-kit/blade-icons)

[GitHub - blade-ui-kit/blade-icons: A package to easily make use of SVG icons...](https://github.com/blade-ui-kit/blade-icons)
A package to easily make use of SVG icons in your Laravel Blade views. - GitHub - blade-ui-kit/blade-icons: A package to easily make use of SVG icons in your Laravel Blade views.

via Sage theme: composer require blade-ui-kit/blade-heroicons

Manually add to your providers:
BladeUI\Icons\FactoryServiceProvider::class,

Run wp acorn vendor:publish

Which provider or tag's files would you like to publish?:
  [0 ] Publish files from all providers and tags listed below
  [1 ] Provider: BladeUI\Heroicons\BladeHeroiconsServiceProvider
  [2 ] Provider: BladeUI\Icons\BladeIconsServiceProvider
  [3 ] Provider: Log1x\AcfComposer\Providers\AcfComposerServiceProvider
  [4 ] Provider: Log1x\Poet\PoetServiceProvider
  [5 ] Provider: Roots\Acorn\Providers\AcornServiceProvider
  [6 ] Tag: acorn
  [7 ] Tag: blade-heroicons
  [8 ] Tag: blade-heroicons-config
  [9 ] Tag: blade-icons
  [10] Tag: config
 > 0
Include in your blade template:
<x-heroicon-o-adjustments class="w-6 h-6 text-gray-500"/>

**Comment by driesvints** [comment]
Hey @minemindmedia, glad you found a solution 👍 

For these sorts of questions it's indeed probably best that you try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
