### ISSUE TITLE
Unknown Blade component

### ISSUE THREAD

**Issue by brandon-9** [driesvints/blade-icons#189]
### Library version

v1.2.2

### Laravel version

v9

### PHP version

8.0

### Description

PHPStorm constantly notifies "Unknown Blade component" when using an icon. Any suggestions? Are any stubs possibly available? Thanks!

### Steps to reproduce

Insert blade icon in blade view.

**Comment by driesvints** [comment]
I'm not sure. I don't work with PHPStorm myself anymore. Afaik it's not possible to know a component if it doesn't exists as a file. Blade icons aren't actual components but rather virtual registered through `Blade::component()`.
