### ISSUE TITLE
How Can I Use "wire:click" with @svg Syntax?

### ISSUE THREAD

**Issue by reasecret** [driesvints/blade-icons#193]
I was using standard svg icons like this:
`<svg wire:click="action">...</svg>`

I tried to use `@svg('gmdi-check-circle-o', 'w-5 h-5', wire:click="action")` but not worked (`syntax error, unexpected ':', expecting ')'`).

Or should I use `<x-gmdi-check-circle-o />` syntax? 

PS: @ svg syntax looks like more useful for me.

**Comment by myregistration** [comment]
I think you could use wire-click on an element like div or span that contains the `@svg`

`<div wire:click="">@svg('gmdi-check-circle-o', 'w-5 h-5')</div>`

or try using the other alternative with with x-icon before the name of the icon, like this for camera icon

`<x-icon-camera  class="w-5 h-5" wire:click="" />`

**Comment by reasecret** [comment]
> I think you could use wire-click on an element like div or span that contains the `@svg`
> 
> `<div wire:click="">@svg('gmdi-check-circle-o', 'w-5 h-5')</div>`
> 
> or try using the other alternative with with x-icon before the name of the icon, like this for camera icon
> 
> `<x-icon-camera class="w-5 h-5" wire:click="" />`

Yes we can use wire:click with container element. I just wondered usage with @svg for writing less code. Looks like we should use like laravel components.

**Comment by driesvints** [comment]
Like @myregistration suggest, the correct way is to use the wire click on a container element. I don't recommend setting it on the icon directly.
