### ISSUE TITLE
php artisan icons:cache Does not work on vapor as vapor do not have those write access to those dir

### ISSUE THREAD

**Issue by msonowal** [driesvints/blade-icons#195]
### Library version

v1.3.0

### Laravel version

latest laravel 9

### PHP version

8.1

### Description

Any alternate way of caching for laravel vapor or serverless environments to use?

Maybe we can cache the manifest and use a different dir so that vapor will upload/deploy the file along with the application code as for now it ignores that dir even though we have generated the command in composer dump auto load scripts 

### Steps to reproduce

just deploy in laravel vapor

**Comment by driesvints** [comment]
The best we can do probably is to indeed make the manifest path configurable so you can point to a dir that's committed. I'd accept a PR for that. Thanks!
