### ISSUE TITLE
Svg by name "home" from set "default" not found

### ISSUE THREAD

**Issue by TrevorSlobodnick** [driesvints/blade-icons#199]
I can't get the "home" icon I downloaded from Feather to display ([Link](https://feathericons.com/?query=home))

These are the steps I've done so far:

1. I followed the install instructions from the readme
2. In the "resources" directory, I created a new directory called "svg"
3. I placed "home.svg" inside the newly created "svg" directory
4. I attempted to display the icon using `<x-icon name="home" />` and `@svg('home')`

They both gave the same error: 'Svg by name "home" from set "default" not found'.

Am I missing something?

**Comment by driesvints** [comment]
Hey @TrevorSlobodnick, I think you missed this step from the install instructions?

> Then, publish the configuration and uncomment the default icon set:

https://github.com/blade-ui-kit/blade-icons#installation

**Comment by TrevorSlobodnick** [comment]
@driesvints No unfortunately I did that step. The only thing that might have caused an issue is I ran the command `php artisan vendor:publish --tag=blade-icons` first, then I uncommented the default set. Is it supposed to be the other way around?  

Regardless, I did find a solution.

Running `php artisan vendor:publish --tag=blade-icons --force` did the trick.

**Comment by driesvints** [comment]
No you should indeed first publish. It's odd because everything works when I follow the install instructions. No idea why it doesn't for you

**Comment by harrison-drift** [comment]
I wa banging my head against this same error this morning. Turns out I'd just spelled my file name entirely wrong. :coffee:
