### ISSUE TITLE
Error before publishing config.

### ISSUE THREAD

**Issue by lukasoppermann** [driesvints/blade-icons#2]
Hey, I get the following error when trying to publish the config.

>   [ErrorException]
>   array_merge(): Argument #1 is not an array

I get it because of this line:

``` php
$config = array_merge(config('blade-svg'), [
```

This fixes it:

``` php
$config = array_merge((array) config('blade-svg'), [
```

Once I run `art vendor:publish --provider="BladeSvg\BladeSvgServiceProvider"` the line can be removed, as now it returns an array.

**Comment by adamwathan** [comment]
Thanks, fixed.
