### ISSUE TITLE
Support for viewBox sizing

### ISSUE THREAD

**Issue by mattkoch614** [driesvints/blade-icons#21]
Is there a way to specify the size of the SVG viewBox or otherwise size the SVG? For example, I'm using a set of SVG files from https://useiconic.com/open  and I'd like to resize them.

Perhaps I'd just do:

`` @svg('people', ['width' => '15', 'height' => '15']) `` ?

**Comment by adamwathan** [comment]
The easiest way by far is to size them with CSS, by applying a class that
sets the width and height 👍🏻

**Comment by mattkoch614** [comment]
Thanks, I'll give this a shot. Appreciate the quick reply.
