### ISSUE TITLE
Spritesheet / symbol

### ISSUE THREAD

**Issue by strarsis** [driesvints/blade-icons#22]
@adamwathan: I want to inline the same (quite complex) SVG multiple times on a page so 
I can style it differently using page CSS.
Despite gzip I think using a symbol for referencing to the same inlined SVG would be the best approach.
Can I do this with blade-svg? I want to prevent duplicate SVG markup.

**Comment by driesvints** [comment]
Is the `@sprite` directive from the next version what you need? You can pass different classes/style attributes to each directive: https://github.com/adamwathan/blade-svg/tree/next-version#sprite-sheets

**Comment by strarsis** [comment]
Well, with HTTP2 (and Let's Encrypt) there isn't really a need for spriting anymore.

**Comment by driesvints** [comment]
Okay. Gonna close this one already then. Thanks for replying 👍
