### ISSUE TITLE
Nested filepaths possible?

### ISSUE THREAD

**Issue by E-VANCE** [driesvints/blade-icons#25]
Just a quick question since I am getting `File does not exist`-errors when trying to use the `@svg`-directive like this:

`@svg('icons/cards/info-blue')`

Do all the files have to sit in the same directory or is there any way I can use nested / multi-level paths?

Many thanks for your efforts with Blade SVG, very much appreciated!

**Comment by bbashy** [comment]
You should use dot notation for nested paths.
```
@svg('icons.cards.info-blue')
```
