### ISSUE TITLE
Add auto discover for Laravel and allow absolute paths

### ISSUE THREAD

**Issue by DevDavido** [driesvints/blade-icons#26]
Thank you Adam for this useful package! 
I started using it and I noticed it doesn't allow absolute paths for the svg_path option for example like most other packages do. I wanted to use the public_path() or storage_path() helper to define the path.
A nice bonus would be having the auto discovery functionality from Laravel too.
Would you also accept a PR for such changes?

**Comment by driesvints** [comment]
Heya, auto discovery was already added in the past it seems. Using the path helpers in config files isn't possible with Laravel I'm afraid.
