### ISSUE TITLE
Possibility to transition between svgs

### ISSUE THREAD

**Issue by haelbichalex** [driesvints/blade-icons#27]
Any tips on how to fade transition between two svgs "icon-neutral.svg" and "icon-hover.svg"?

**Comment by meduzen** [comment]
This is out of scope of this Laravel package, but you can search for [SVG morphing](https://www.duckduckgo.com/?q=svg+morph) or look after the GreenSock [MorphSVG plugin](https://greensock.com/morphSVG).

**Comment by driesvints** [comment]
Bit out of scope of this package indeed I'm afraid.

**Comment by cawecoy** [comment]
I needed the same thing, now I want to share my solution: https://github.com/cawecoy/alternate-svg-on-hover-css
