### ISSUE TITLE
Package requires publishing the config as the default config is not being read

### ISSUE THREAD

**Issue by spaceemotion** [driesvints/blade-icons#28]
Hey, first of all; thanks for this package!

I was wondering why my SVG logo was not being rendered as an inline image, as your default config clearly states `'inline' => true`.

Turns out, your SvgFactory has an additional `$config` that is not being populated with the out-of-the-box config.

Simply publishing the config works as a "fix".

**Comment by adamwathan** [comment]
Fixed and tagged v0.3.0, thanks.

**Comment by spaceemotion** [comment]
Thanks for the quick fix!
