### ISSUE TITLE
Where would I put the svg's

### ISSUE THREAD

**Issue by abrhambas01** [driesvints/blade-icons#29]
The Readme doesn't give me the location to put the svg's

**Comment by brandonpittman** [comment]
If you did around in the config, you’ll see they go in resources/svg. I think. It’s in the config.

**Comment by abrhambas01** [comment]
@brandonpittman, Oh thank you buddy. I didn't see that.

**Comment by abrhambas01** [comment]
@brandonpittman, I  get File does not exist at path error

**Comment by sinrise** [comment]
I'm having the same issue. It doesn't seem to be using the config file... are we supposed to create a new config file in the root/config, or does the readme reference the config file inside vendor/nothingworks... folder? I created a folder using the path specified in that config file and the html output does not reference the resources/assets/svg folder.
