### ISSUE TITLE
syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF)

### ISSUE THREAD

**Issue by djekl** [driesvints/blade-icons#3]
Hi @driesvints trying this out today, and I wasn't able to get this to work. I got the following error;
https://flareapp.io/share/95J9pZ7r#F48

To reproduce I created a new Laravel project, required your package, and then added `<x:heroicon-o-home>` to the `home.blade.php` file. I originally tried adding this to the view, but got the error, so to get the flare share, I just removed all the noise. Same error was thrown as you can see.

I don't know if this is an issue with your package, or Laravel itself. I had a quick poke around, and couldn't see anything that should cause this issue…

**Comment by ciungulete** [comment]
Close the brackets <x:heroicon-o-adjustments/>

**Comment by ciungulete** [comment]
Close tag <x:heroicon-o-adjustments/>

**Comment by djekl** [comment]
Thanks, I missed that!
