### ISSUE TITLE
Alter when config gets set to allow for Middleware

### ISSUE THREAD

**Issue by jfsullivan** [driesvints/blade-icons#31]
It looks like the config that is used in the package gets locked in during the register method of the ServiceProvider.  I would like to alter the svg_path in my Middleware to allow for different locations for different tenants but since it is set in the ServiceProvider any changes I make to it in my Middleware are disregarded.

**Comment by driesvints** [comment]
The next version of the package will allow to define multiple icon sets and you can add them ad-hoc so you could add separate sets with different paths if you want: https://github.com/adamwathan/blade-svg/pull/50
