### ISSUE TITLE
failed to open stream

### ISSUE THREAD

**Issue by evd1ser** [driesvints/blade-icons#32]
Don't work save sprite, failed to open stream: No such file or directory
'spritesheet_path' => 'resources/assets/svg/spritesheet.svg', //not found and not create =(

**Comment by adamwathan** [comment]
You have to create the spritesheet yourself, so if you haven’t created one
that would explain the error. I would recommend using inline SVGs anyways
honestly.

**Comment by evd1ser** [comment]
I thought the plugin will automatically create it, sorry
