### ISSUE TITLE
Add markup into SVG

### ISSUE THREAD

**Issue by strarsis** [driesvints/blade-icons#33]
Is it possible to add markup in a SVG body, like blade components?

```php
@svg('some.svg')
Extra markup that goes into SVG.
@endsvg
````

**Comment by adamwathan** [comment]
Can't do anything like that with the package currently no.

**Comment by driesvints** [comment]
Also not in the next version but I do am curious about the idea. What would you do with this?

**Comment by driesvints** [comment]
Going to close this one. Definitely feel free to provide feedback when you can.
