### ISSUE TITLE
Blade SVG on sharing host not render

### ISSUE THREAD

**Issue by princeofforest** [driesvints/blade-icons#36]
On sharing host, the blade Svg doesn't render, i don't know if it does not allow me to run artisan on terminal, php artisan vendor:publish --provider="BladeSvg\BladeSvgServiceProvider" , so i created my copy the config file from my localhost. Then the bladesvg didn't render.

**Comment by de-it-rick** [comment]
Having the same issue.
`@svg('plattegrond', '')` works perfectly fine on localhost, then I pushed the commits to the server and in the live environment it only echoes `@svg('plattegrond', '')`. 
I ran `composer install` and the other installation commands again but no luck unfortunately...

**Comment by MrAlexEvers** [comment]
I've had the same issue, but I noticed that when I reuploaded the actual views that use @svg, they will show up. the views were probably still cached from before I got BladeSvg working.

**Comment by driesvints** [comment]
Always make sure you run `php artisan view:clear` when deploying.
