### ISSUE TITLE
Default attributes

### ISSUE THREAD

**Issue by stephenturvey** [driesvints/blade-icons#37]
I can add default classes in the config, but what about default attributes?

At the moment I'm having to type out the same attributes each time, eg:

`@svg('my-icon', 'text-red', ['aria-hidden' => 'true', 'viewBox' => '0 0 24 24'])`

**Comment by driesvints** [comment]
Yeah, I can definitely see that being useful.

**Comment by driesvints** [comment]
I've implemented this here: https://github.com/blade-ui-kit/blade-icons/pull/115

However, it's not possible to override existing attributes on icons. They should be removed first before new ones are applied.
