### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by Gummibeer** [driesvints/blade-icons#4]
I would like to add https://fontawesome.com icons. Because the SVGs are copied to this repo we could only add the free ones!? Or should we use an artisan command to copy/use the ones from a local pro installation?
I would also like to know how we should handle the different styles? By a prefix? `fontawesome-solid-` `fontawesome-duotone-`?

**Comment by driesvints** [comment]
Font awesome already provides a very easy way to include its icons in your project using the `<i>` element so I have no plans to add it to Blade Icons. 

However, the next update of Blade Icons will make it easier for you to add your own sets if you want to.
