### ISSUE TITLE
Feature Request: Accept blade variables as SVG name

### ISSUE THREAD

**Issue by minthemiddle** [driesvints/blade-icons#42]
I would love to show SVGs based on a value in a model's attribute.

Here is what I tried:
`@svg({{ $user->type }})` which throws an ugly error (`syntax error, unexpected '<' (View: `).

Browsing through `blade-svg`'s tests, this use case is not being considered up till now.
I could not find a work around and it might be a nice addition.

**Comment by njoguamos** [comment]
Had the same issue.

**Comment by njoguamos** [comment]
Try using the svg helper directly.

```php
{{ svg_image($user->type) }}
```

That should work.

**Comment by driesvints** [comment]
Using the curly braces in Blade directives isn't supported by Blade itself.
