### ISSUE TITLE
Call to undefined function BladeSvg\snake_case()

### ISSUE THREAD

**Issue by yaquawa** [driesvints/blade-icons#43]
I've got an error at:
```
vendor/nothingworks/blade-svg/src/Svg.php:37
```

Laravel 6 has deprecated string helper, you should use `\Illuminate\Support\Str::snake` instead.

**Comment by Luoti** [comment]
It was actually fixed some time ago, but there is no new version released since then.

https://github.com/adamwathan/blade-svg/pull/41

**Comment by yaquawa** [comment]
@Luoti Thanks!
