### ISSUE TITLE
Specifying different path and filename

### ISSUE THREAD

**Issue by fri3ndly** [driesvints/blade-icons#45]
I'm having difficulty showing an inline SVG for a path and filename not in the /svg directory

Could we perhaps have a way of avoiding using the svg directory and passing a directory and SVG filename to the getSvg function like this:
```

   public function getSvgUrl($name)
    {
        return $this->svgCache->get($name, function () use ($name) {
            return $this->svgCache[$name] = trim($this->files->get(public_path($name)));
        });
    }

```

**Comment by driesvints** [comment]
This unfortunately isn't possible right now but with the next version you'll be able to define multiple icon sets and thus also multiple paths. Is that what you need? https://github.com/adamwathan/blade-svg/pull/50

**Comment by driesvints** [comment]
Going to close this one. Feel free to provide feedback when you can.
