### ISSUE TITLE
How to override the width and height?

### ISSUE THREAD

**Issue by umairxiq** [driesvints/blade-icons#52]
How can i overide height and width of svg. e.g

<inline-svg name="edit" width="25" height="25"></inline-svg>

Help me out in syntax. Thanks

**Comment by driesvints** [comment]
Do you mean you have an existing width and height defined? Can you show us some code examples and the SVG you're using?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
