### ISSUE TITLE
SVG with style tag + Vue

### ISSUE THREAD

**Issue by EvilLooney** [driesvints/blade-icons#53]
Hi,

I am wondering if I am going about this the wrong way.

I have SVGs with embedded styles (`<style>...</style>`) but I cannot use them if I am including them inside a Vue app as Vue will complain:
_Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed._

I have found the way to counter this would be to change the `<style>` tags to `<svg:style>` inside my SVGs. However, the following function will place my given SVG class in both elements:
https://github.com/adamwathan/blade-svg/blob/600269d60efe52bf9fc2cc610b21744cd69425df/src/Svg.php#L55-L62

Shouldn't the function return :
`return \Illuminate\Support\Str::replaceFirst('<svg', '<svg ' . $this->renderAttributes(), $this->factory->getSvg($this->imageName));`
?

Or maybe I am doing it wrong.

Thanks.

**Comment by driesvints** [comment]
This is a bit out of scope of this library I'm afraid as we can't control the elements that you place inside your svgs.

**Comment by EvilLooney** [comment]
Hmmm ok.

But maybe it should be noted to the documentation that this library cannot handle SVG namespaces as it takes valid markup and renders it gibberish:

```
// SVG 
<svg:svg width="300px" height="200px">
    <svg:circle cx="150" cy="100" r="50" fill="#ff0000"/>
</svg:svg>

// Blade
{{ @svg('/path/to/file', 'myclass') }}

// Output
<svg class="myclass":svg width="300px" height="200px">
    <svg class="myclass":circle cx="150" cy="100" r="50" fill="#ff0000"/>
</svg:svg>
```

**Comment by driesvints** [comment]
Why would `<svg:svg` be valid?

**Comment by EvilLooney** [comment]
Well I didn't write the spec but I see it being allowed:
[https://www.w3.org/TR/SVG2/struct.html#Namespace](url)
[https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course](url)

**Comment by driesvints** [comment]
I see. Thanks for making me aware.

Does the parent always use `<svg:svg` or could it be something else as well like `<svg:foo`?

**Comment by EvilLooney** [comment]
It's actually a prefix and it's reused for each element. I believe if it's different from `svg`, it needs to be defined with the `xmlns` attribute:

```
<foo:svg xmlns:foo="http://www.w3.org/2000/svg" width="300px" height="200px">
    <foo:circle cx="150" cy="100" r="50" fill="#ff0000"/>
</foo:svg>
```

**Comment by driesvints** [comment]
Well, I wouldn't need this myself but would be open to prs that implement this in a nice and clean way. We're currently undergoing some transition however with https://github.com/adamwathan/blade-svg/pull/50 so you might wanna hold off until that's done.

**Comment by EvilLooney** [comment]
No problem.

I understand that this will never be used 99.99% of the time. I just noticed it when trying to find a workaround with a problem on Vue's end.

**Comment by driesvints** [comment]
I'm going to close this as I don't intend to implement this myself any time soon but happy to look at a PR if anyone wants to send one in 👍
