### ISSUE TITLE
ViewException with Blade components

### ISSUE THREAD

**Issue by fredericseiler** [driesvints/blade-icons#54]
Hi,

I'm testing the `next-version` branch, and I can't figure out how to use the Blade components.

Environment:
- Laravel version: 7.12.0
- PHP version: 7.4.3
- No config cache

My `blade-icons.php` config file:

```php
return [
    'sets' => [
        'default' => [
            'path' => 'resources/svg',
            'prefix' => 'icon',
            'class' => '',
        ],
    ],
    'class' => '',
];
```

I have an `account.svg` inside of `resources/svg`.

```blade
@svg('account') {{-- renders correctly --}}

{{ svg('account') }} {{-- renders correctly --}}

<x-icon-account/>

{{--

Facade\Ignition\Exceptions\ViewException
Unable to locate a class or view for component [icon-account].

--}}
```

Am I missing something ?

**Comment by driesvints** [comment]
Hmm that should work just fine. Did you try clearing your views?

**Comment by fredericseiler** [comment]
Views cleared, no changes.

**Comment by driesvints** [comment]
It's weird because I'm using atm as such and it works for me. So I'm wondering what's different for you. You're sure you're using the latest commit from the next version branch?

**Comment by fredericseiler** [comment]
I installed it 30 minutes ago, but to be sure:

`composer.json`
```json
{
    ...
    "require": {
        ...
        "nothingworks/blade-svg": "dev-next-version"
    },
    ...
}
```

```bash
$ composer update
Updating dependencies (including require-dev)         
Nothing to install or update
...
Discovered Package: nothingworks/blade-svg

$ php artisan view:clear
Compiled views cleared!
```
I still got a `ViewException`.

**Comment by fredericseiler** [comment]
Has it something to do with the fact that the Factory is defined as a singleton in the Service Provider but is actually never called (so the registerComponents() method can't do its magic) ?

**Comment by fredericseiler** [comment]
I added this inside the `registerFactory()` of `BladeInconsServiceProvider` to instantiate the singleton, and it works now:

```php
private function registerFactory(): void
{
    /* ... */

    $this->app->make(Factory::class);
}
```

**Comment by fredericseiler** [comment]
Or just bind the instance:

```php
private function registerFactory(): void
{
    $config = $this->app->make('config')->get('blade-icons');

    $factory = new Factory(new Filesystem(), $config['class']);

    foreach ($config['sets'] as $set => $options) {
        $options['path'] = $this->app->basePath($options['path']);

        $factory->add($set, $options);
    }

    $this->app->instance(Factory::class, $factory);
}
```

**Comment by driesvints** [comment]
@fredericseiler thanks, that's a good tip. Just pushed a commit which should fix this. Not sure why I didn't caught this before.

**Comment by fredericseiler** [comment]
Fixed indeed, thank you!
