### ISSUE TITLE
Provide more accessibility helpers

### ISSUE THREAD

**Issue by Insolita** [driesvints/blade-icons#56]
Accordingly 
  https://www.deque.com/blog/creating-accessible-svgs/
  https://css-tricks.com/accessible-svgs/

We need a simple way to add default "aria-hidden='true'" attribute when icons used just like icons near descriptive texts
And ability to set descriptive title and text inside a svg tag if we need to add some description
for ex.

```
<x-icon-o-bell  "role"="image">
   <title>Notificatons</title>
</x-icon-o-bell>
```
or

```
@svg('heroicon-o-bell', ['class'=>'w-8 h-8', 'role'=>'image', 'a11y-title'=>'Notifications', 'a11y-desc'=>'Show recent notification list'])
```

**Comment by driesvints** [comment]
Gonna close this as a duplicate for https://github.com/adamwathan/blade-svg/issues/12

Please add any additional info you have over there, thanks.
