### ISSUE TITLE
Installing the package breaks other package's directives

### ISSUE THREAD

**Issue by JuanDeLeon** [driesvints/blade-icons#60]
I haven't been able to figure out why, but as soon as I install this package and make any change to my view (or do `php artisan view:clear` as well), it no longer recognizes spatie/laravel-permission directives.

My view just prints out the directives as text, like this:

@hasanyrole('Administrador|Ventas')
<x-menu.menu-item></x-menu-item>
@endhasanyrole

I'm using Laravel 7.16

**Comment by driesvints** [comment]
Hey @JuanDeLeon. Looks like you didn't close the component properly:

```blade
@hasanyrole('Administrador|Ventas')
<x-menu.menu-item/>
@endhasanyrole
```

**Comment by JuanDeLeon** [comment]
Hey, thanks for the response. I'm sorry I copied it wrong, but I even simplified my code and still getting this with the following:

sidebar-menu.blade.php
![Captura de Pantalla 2020-06-21 a la(s) 10 58 10](https://user-images.githubusercontent.com/13142634/85229250-45813b00-b3ae-11ea-89e4-78865ad150e0.png)

components/menu/menu-item.blade.php
![Captura de Pantalla 2020-06-21 a la(s) 10 59 03](https://user-images.githubusercontent.com/13142634/85229254-4914c200-b3ae-11ea-8ec4-ed83408abbd7.png)

result
![Captura de Pantalla 2020-06-21 a la(s) 10 59 11](https://user-images.githubusercontent.com/13142634/85229255-4b771c00-b3ae-11ea-9d9e-0f7e0e9c069a.png)

(Using the heroicons extension btw, but I don't think that's related to the issue.)

Edit: I just reverted all code (i.e. not using any icon component at all) and the issue persisted. I removed this package and the issue was gone.
So it seems to be a directive's conflict? I don't have that much experience there, so I still cannot figure it out.

**Comment by driesvints** [comment]
Heya, it seems you're still referencing the icon incorrectly. Please note that you need to use a self closing tag (see my example) and not a slotted component as in your example.

**Comment by driesvints** [comment]
Also, you're referencing the icon as `o-home`. Is this `o-home.svg` file present in your `resources/svg` directory? Can you please post your `blade-icons.php` config file?

**Comment by JuanDeLeon** [comment]
Tried with self closing tags but it made no difference.
Should I **not** be using these x-icon components inside my menu/menu-item.blade.php component?

Yes the svg is present. 
Icons are actually shown as expected, so I guess the config is correct. 
Here it is:
(o-home.svg doesn't show but it's down below there, any icon I try in this list is shown correctly, but the permission directives are still ignored)

![Captura de Pantalla 2020-06-21 a la(s) 11 55 26](https://user-images.githubusercontent.com/13142634/85230482-1ff82f80-b3b6-11ea-9860-be63019f14d5.png)

**Comment by driesvints** [comment]
hmm that's super strange. Can you post the contents of `o-home.svg`?

**Comment by JuanDeLeon** [comment]
Sure, raw pasted:

```
<svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/>
</svg>
```

Adding source code result from browser. Altered the `<a>` classes a bit (and also using the s-adjustments icon here, but overall code is exactly the same). I'm pretty sure there's no typo or anything weird in there.

![Captura de Pantalla 2020-06-21 a la(s) 12 18 19](https://user-images.githubusercontent.com/13142634/85231006-6307d200-b3b9-11ea-923d-c3157eef0def.png)

**Comment by driesvints** [comment]
I'm a bit stumped sorry. Everything seems to be okay code-wise. I'll need to fully test the package to know for sure what's going on but I don't have time for that atm, sorry. Appreciating any help here.

**Comment by xewl** [comment]
I just noticed this one too; after switching from blade-svg (I was using the preview version, which worked fine)
The blade directives of `spatie/laravel-permissions` just stopped working after switching to this package from the preview branch.
Didn't matter if there was an icon in them or not; Lrvl/Blade just stops converting those to PHP.
(those, as in anything  ```@role```  related)

**Update 2020-06-28**: For some reason, it now works again for me. 👌 (I tend to do composer update a lot, so..)

Also; [separate issue, if not related]
the default classes are not used anymore when adding another one via the class="" attribute.
Not overriding the class attribute, works as expected.
(unlike before in the preview, and the statement that it should append it @ readme)
Edit: Made a separate issue: #61

**Comment by driesvints** [comment]
@xewl can you post a separate issue for that? Please be very detailed in how your config, code etc looks and what you expect that needs to happen.

**Comment by driesvints** [comment]
Hi all. I tried installing the package with blade icons and trying to use the directives together with the icons but everything works fine for me. I think it's best that you continue this on a different support channel like the Laracasts or Laravel.io forums or Laravel Discord.

```php
                @hasanyrole('writer|admin')
                    I am either a writer or an admin or both!
                    <x-icon-camera class="h-5 fill-current"/>
                @else
                    I have none of these roles...
                    <x-icon-camera class="h-5 fill-current"/>
                @endhasanyrole
```
