### ISSUE TITLE
Class attribute gets overridden instead of appended

### ISSUE THREAD

**Issue by xewl** [driesvints/blade-icons#61]
- Library Version: 0.4.0
- Laravel Version: 7.17.2
- PHP Version: 7.4.6 @ Ubuntu 18.04 WSL2

### Description:
When adding a custom class, the default classes are not added anymore.
Note that this worked perfectly in the preview build you had previously @ Adam's blade-svg.

_Readme says:_
You can also pass classes to your icon components **(default classes will be applied as well)**:
`<x-icon-camera class="icon-lg"/>`

### Steps To Reproduce:
`<x-icon-calendar-lock />`
returns:
`<svg class="icon sl-micro" ... >...</svg>`

but, 
`<x-icon-calendar-lock class="text-orange-400" />`
returns:
`<svg class="text-orange-400" ... >...</svg>`

What I expected:
`<svg class="icon sl-micro text-orange-400" ... >...</svg>`

#### Partial content of `resources/svg/icon/streamline-micro/calendar-lock.svg` (!; licensing):

```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" viewBox="0 0 10 10">
  <g>
    <path .... />
  </g>
</svg>
```

#### My Config (blade-icons.php)
```php
<?php
return [
    'sets' => [
        'streamline-micro' => [
            'path' => 'resources/svg/icon/streamline-micro',
            'prefix' => 'icon', // 'icon-sl-micro',
            'class' => 'sl-micro'
        ],

        'streamline-light' => [
            'path' => 'resources/svg/icon/streamline-light',
            'prefix' => 'icon-sl-light',
            'class' => 'sl-light'
        ],

    ],
    'class' => 'icon',
];
```

**Comment by driesvints** [comment]
Fixed in https://github.com/blade-ui-kit/blade-icons/commit/d53025a1ad573f7c16e822aeca44e42127df463d

I'll tag a release soon. Thanks for reporting!
