### ISSUE TITLE
Using icons hosted on remote storage

### ISSUE THREAD

**Issue by nathan-io** [driesvints/blade-icons#72]
Hello, thanks for this amazing package!

I see that we can customize the `path` for a given icon set, but what if the icons are not stored on the application server?

In our case, they would be served from our remote S3 storage.

In addition to `path`, are we able to define the URL?

**Comment by driesvints** [comment]
Hey Nathan. I like the idea of maybe using Laravel's Flysystem integration to pull an icon set. I'll mark this as a feature request. At the moment I don't have time to work on this myself but would appreciate PRs for this.

**Comment by nathan-io** [comment]
Yes, it would indeed be great if we could define the filesystem disk the icon files are hosted on.

I'll see if someone can help us with a PR.

Thank you.

**Comment by driesvints** [comment]
This will be in the next release.
