### ISSUE TITLE
Default classes for 3rd party icon packages

### ISSUE THREAD

**Issue by ragulka** [driesvints/blade-icons#73]
Would it be possible to provide default classes for icons provided by packages? For example, when I want to use `brunocfalcao/blade-feather-icons`, and want to set the default class in the `config/blade-icons.php` like this:

```php
'feathericons' => [
    'class' => 'w-10 h-10'
]
```

It seems to override the set provided by the package, so I get the error:
```
Undefined index: path
```

The use case would be that I'm using different sets and packages for different purposes, and I would avoid repetition if I could set the default size.

**Comment by driesvints** [comment]
Hey @ragulka. When overriding config you need to provide the full config, it doesn't merges configs. You'll need to point the path to the icon set from the package: https://github.com/brunocfalcao/blade-feather-icons/blob/master/src/BladeFeatherIconsServiceProvider.php#L14

Does that work for you?

**Comment by ragulka** [comment]
@driesvints yeah I think I can make that work, thanks!
