### ISSUE TITLE
Tooltip support

### ISSUE THREAD

**Issue by jericopulvera** [driesvints/blade-icons#77]
Hello, 

I'm trying to make this work with bootstrap 4 but it does not work properly.

```
   <div data-toggle="tooltip" title="Tooltip Test">Wallet Balance
        <x-zondicon-question style="width: 15px; margin-left: 2px;" />
    </div>
```

**Comment by driesvints** [comment]
Heya, that's probably a question for a support channel like Laracasts or Laravel.io. Please try there and keep this issue tracker for issues specifically to Blade Icons. Thanks.
