### ISSUE TITLE
AlpineJS conditional classes

### ISSUE THREAD

**Issue by ju5t** [driesvints/blade-icons#80]
First of all, cool package! Very helpful!

I'm running into one problem and I'm not 100% sure this is a bug or a lack of knowledge on my end. I'd like to give the component a conditional class in AlpineJS, such as:

```
:class="{ 'text-gray-600': open }"
```

I haven't had the time yet to dig into this extensively, but I'm guessing this is related to the attribute parsing done in `blade-icons`. Does anyone have a suggestion how to pass the conditional class to the icon?

**Comment by driesvints** [comment]
Can you copy paste the full icon tag?

**Comment by ju5t** [comment]
I would normally do this:

```
<x-zondicon-user-group class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-500 group-focus:text-gray-600 transition ease-in-out duration-150" :class="{ 'text-gray-600': open }" />
```

This returns an error, as the output is:

```
<?php $component->withAttributes(['class' => \Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute({ 'text-gray-600': open })]); ?>
```

Moving it in front doesn't work, as I'm overriding the class (although it feels a little sketchy what I'm doing, I must admit)

**Comment by driesvints** [comment]
This isn't exactly a Blade Icons issue but rather an incompatibility with Blade components from Laravel and Alpine.js syntax. I'm not really sure how to solve this but it's probably best that you either open an issue on the Alpine.js issue tracker or a discussion on the laravel repo (not an issue). Or try a support channel like discord, laracasts forums etc.

**Comment by ju5t** [comment]
@driesvints thanks, I guess it turned out to be my lack of knowledge this time :-)

**Comment by csoutham** [comment]
@ju5t What was your solution for this in the end please?

**Comment by ju5t** [comment]
If you use `x-bind:class` it works.

Credits: https://github.com/alpinejs/alpine/discussions/722

**Comment by Enaah** [comment]
Another solution is `::class`

Source: https://laravel.com/docs/8.x/blade#escaping-attribute-rendering

**Comment by driesvints** [comment]
@Enaah yeah that was added pretty recently so this shouldn't be an issue anymore.

**Comment by troccoli** [comment]
Thanks @Enaah, that saved my day
