### ISSUE TITLE
Render by string html (like {!! $icon !!})

### ISSUE THREAD

**Issue by isaiascardenas** [driesvints/blade-icons#89]
Hi guys,

First thanks for this package!!

I'm trying to render an icon by string html. I have something like:

```php
// on Controller, Livewire render method or ViewComposer (AppServiceProvider::boot)

$myIcon = '<x-css-search class="w-6 h-6 text-red-700"/>';

return view('my-view', compact('myIcon'));
```
then in my-view.blade.php:

```html
<div>
  {{-- this render without problem! --}}
  <a>
    <x-css-search class="w-6 h-6 text-red-700"/>
  </a>

  {{-- this not :c --}}
  <a>
    {!! $myIcon !!}
  </a>
<div>
```

Do you have any ideas why is not render $myIcon?

I'm using:
* Laravel 7.2
* blade-ui-kit 0.1
* blade-icons 0.4.4

**Comment by isaiascardenas** [comment]
Solved using Directive instead

```php
$myIcon = 'css-search';

return view('my-view', compact('myIcon'));
```

```php
<div>
  <a>
    @svg($myIcon, ['class' => 'w-6 h-6 text-red-700'])
  </a>
</div>
```

**Comment by driesvints** [comment]
Hey @isaiascardenas. You can't render blade components like that. They have to be in the blade file itself for the compiler to parse them. You could use the helper to render it in the controller and pass it as a string. That would normally work.
