### ISSUE TITLE
Automatic Sprite Sheet

### ISSUE THREAD

**Issue by OwenMelbz** [driesvints/blade-icons#9]
Is it possible to automatically create optimised sprite sheets?

For example if you set `'automatic_spritesheet' => true` when you use `@icon('cog')` it builds up a collection of the svgs used, then it prints out the spritesheet after the body, based on only the icons you've picked? So you can have individual .svg files in your asset folder still?

Thanks :)

**Comment by lukasoppermann** [comment]
Why don't you use a gulp flow for this? I just build my sprites in my gulp build step. I think this feature would be a bit over the top for this package.

Also, you would have many different sprites (one per page). If you use the `inline` option you can also use individual icons and have no additional requests.

**Comment by OwenMelbz** [comment]
Because not everybody knows enough to delve into gulp? or want to include extra dependencies etc, when a pre-existing dependency (blade-svg) could do it, which would make it a much easier and more flexible for people to handle files in their own way?

You'd have just the 1 spritesheet at the top of the template. Imagine if you had a spritesheet with 30 individual images in it. But Page X only needs 1 image. You'd include them all for that 1 image. By having a dynamic spritesheet you'd be able to only include that 1 sprite into the page. Allowing it to be used multiple times without adding extra page bloat. (not worried about extra requests as thats irrelevant to this package?)

I'm not saying there are not other ways to solve this issue, I'm just saying it would provide an easier way for users to get the benefits of non-static spritesheets resolving code bloat whilst keeping an easy singular files setup.

**Comment by lukasoppermann** [comment]
You are addressing the **optimisation** of svgs, which to me, is not part of this package. It allows you to do the optimisation in any way you want.
1. Using inline will mean no extra requests
2. Building a sprite yourself will mean one request

Including the entire sprite in every page if you only need one should not be an issue:
1. Its a couple kb
2. You should make it cachable by the browser, so it is only 1 request entirely, which is better than 1 request per each page.

It would make this package very complex because:
- do you create the sprite every time, or only if it does not exist?
- how do you track if svg icons have been updated?

I see what you are talking about, but I don't personally think it is the right approach. However, its of course up to Adam in any case.

**Comment by OwenMelbz** [comment]
I'm not suggesting you actually generate a .svg I'm just suggesting that it almost hoists all the requirements to the top e.g you have hundreds of .svg in your library, but you only need the 2 from the template

```
/resources/img/icons
/resources/img/icons/one.svg
/resources/img/icons/two.svg
/resources/img/icons/three.svg
/resources/img/icons/tick.svg
/resources/img/icons/cross.svg
```

```
<body>
@spritesheet();

@icon('cross') //adds the cross.svg to memory for later
@icon('tick')
```

just generates what is effectively like

```
<body>

<svg>
  <defs>
    foreach( $usedIcon as $icon )
    <g id=" $icon->basename ">
        $icon->xml
    <g>
  </defs>
</svg>


<svg>
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#cross"></use>
</svg>

<svg>
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#tick"></use>
</svg>

```

So it only dumps out the definitions of the icons used in the template, almost like how `@section` and `@yield` works

So 
- No you don't create the sprite every time, as there is no sprite to create
- You dont need to track if the svg icons have been updated

**Comment by lukasoppermann** [comment]
But why is this better than just using the `inline` method?

**Comment by OwenMelbz** [comment]
Saves you having the whole XML dumped on the page several times for the same icon

**Comment by lukasoppermann** [comment]
Yeah, well I think this is really not an issue. But that is a personal opinion. Lets just see what Adam thinks.

**Comment by adamwathan** [comment]
I actually would like to make this easier by sticking an array in the config file that lets you specify which icons you are actually using, stripping out the ones you aren't, and caching that on disk somewhere, but not sure when I'll have a chance to play with it.

What I'm personally doing currently is just manually deleting the icons I'm not using from my spritesheet. I keep a complete one in the same folder for reference, and copy the icons back in if I need them. Little bit of manual work but simple as hell still.

**Comment by kiwina** [comment]
I'm looking at this at the moment, and at first glance what about passing a name to the spritesheet helper?
you could then define different sheets for your pages. i use grunt-svgstore to generate the sheet but that cold be change to a command and just like adam mentioned have an array of used icon in groups?

**Comment by kiwina** [comment]
# @OwenMelbz 
here a quick hack on what you say on the icon factory
```
use Symfony\Component\DomCrawler\Crawler;


    private $icons;
    private $config = [
        'build' => false,
    ];

    public function __construct($config = [], $filesystem = null)
    {
        $this->icons = Collection::make();
    }


  public function spritesheet()
    {
        if ($this->config['build'] && !$this->icons->isEmpty()) {
            $svgs = $this->icons->map(function ($item, $key) {
                $crawler = new Crawler($this->getSvg($item));
                $svg = $crawler->filter('svg')->html();
                return sprintf('<symbol viewBox="0 0 1792 1792" id="%s"><title>%s</title>%s</symbol>', $item, $item, $svg);
            });
            return new HtmlString(
                sprintf('<div style="display: none;"><svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">%s</svg></div>', $svgs->implode(' '))
            );
        }
        return new HtmlString(
            sprintf('<div style="display: none;">%s</div>', file_get_contents($this->spritesheetPath()))
        );
    }

    public function icon($name, $class = '', $attrs = [])
    {
        if (is_array($class)) {
            $attrs = $class;
            $class = '';
        }
        $attrs = array_merge([
            'class' => $this->buildClass($class),
        ], $attrs);
        $mode = $this->renderMode();
        if ($mode == 'sprite' && $this->config['build']) {
            $this->icons->push($name);
        }
        return new Icon($name, $mode, $this, $attrs);
    }
```

**Comment by kiwina** [comment]
ps just added the main parts that changed

**Comment by Ajalle** [comment]
I can only upvote for requested feature. There completely no point to include all your svg on page, while it uses only few. If it's hard to implement automatic way to check which images was requested, at least there should be way to setup it somehow using settings.

**Comment by strarsis** [comment]
With HTTP2 spriting/concatenation techniques become less important anyway (they still can make a difference for large numbers).

**Comment by driesvints** [comment]
Is this something that you all still would like? I think passing an array of icon names to the sprite sheet helper as a second argument might be of use.

Btw, please also check out the PR that I made for the next version: https://github.com/adamwathan/blade-svg/pull/50

**Comment by strarsis** [comment]
Well, with HTTP2 (and Let's Encrypt) there isn't really a need for spriting anymore.

**Comment by driesvints** [comment]
After consideration and gathering from the feedback so far I've decided to remove sprite sheet support in the next version.
