### ISSUE TITLE
using x-syntax with blade directives inside class string

### ISSUE THREAD

**Issue by amaelftah** [driesvints/blade-icons#96]
- Library Version: 0.4.5
- Laravel Version:v8.3.0
- PHP Version: 7.4

### Description:
when i use blade directives inside class string for x-icon syntax . it always gives me an undefined variable exception

but when i use @svg it works perfectly

am not sure wither it's a framework bug or package bug

### Steps To Reproduce:
```html
<x-icon-camera class="cursor-pointer @if($someVar) text-blue-500 @endif mr-8 h-10 w-10" /> throws exception

works great
 @svg('ficon-camera', [
      'class' => 'cursor-pointer mr-8 h-10 w-10'. $someVar ? ' text-blue-500 : ''
 ]) 
```

**Comment by driesvints** [comment]
Heya, this syntax isn't supported by Blade components. You cannot use directives on components: https://laravel.com/docs/8.x/blade#managing-attributes

<img width="717" alt="Screenshot 2020-09-24 at 10 10 51" src="https://user-images.githubusercontent.com/594614/94118795-4bc00100-fe4e-11ea-8951-d5dce19a07a2.png">

Try:

```
@if ($someVar)
    <x-icon-camera class="cursor-pointer text-blue-500 mr-8 h-10 w-10" />
@else
    <x-icon-camera class="cursor-pointer mr-8 h-10 w-10" />
@endif
```

**Comment by amaelftah** [comment]
@driesvints thanks a lot
