### ISSUE TITLE
Allow use of `paths` array instead of single `path` property

### ISSUE THREAD

**Issue by faustbrian** [driesvints/blade-icons#98]
On a few projects, I would need the ability to specify multiple paths for icon lookups instead of using multiple sets. Would this be something for which a PR would be accepted or is the use of a single path by design?

```php
        'default' => [
            'path' => [ // or introduce new paths property
                'resources/icons',
                'vendor/companyA/icons/resources/assets/icons',
                'vendor/companyB/icons/resources/assets/icons',
                'vendor/companyC/icons/resources/assets/icons'
            ],
            'prefix' => 'icon',
            'class'  => 'fill-current',
        ],
```

**Comment by driesvints** [comment]
I think that's definitely an option yeah. Might also be easier for some packages like the font awesome one to group their icons.

**Comment by faustbrian** [comment]
Great, will submit a PR on the weekend if no one else has done so by then.

**Comment by driesvints** [comment]
Thanks 🙂 

I have a week vacation next week so hoping to go through all of the open blade icons/blade ui kit stuff then.

**Comment by faustbrian** [comment]
@driesvints would you want to preserve the `path` option so that both `path` and `paths` can be used or should it be only `paths`?

**Comment by driesvints** [comment]
Yeah we definitely need to support the old way and it needs to stay the default. I also see `paths` being used much fewer than its singular equivalent.
